# Generated by Django 6.0 on 2026-01-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='tfno',
            field=models.CharField(max_length=8),
        ),
    ]
